name       : haskell-zip-archive
version    : 0.4.1
release    : 3
source     :
    - https://hackage.haskell.org/package/zip-archive-0.4.1/zip-archive-0.4.1.tar.gz : c5d5c9976241dcc25b0d8753dc526bb1bfef60f30dee38c53a7ae56e6be9b1b1
license    : BSD-3-Clause
component  : programming.haskell
summary    : The zip-archive library provides functions for creating, modifying, and extracting files from zip archives.
description: |
    The zip-archive library provides functions for creating, modifying, and extracting files from zip archives.
builddeps  :
    - haskell-cabal-install
    - haskell-digest-devel
    - haskell-old-time-devel
    - haskell-zlib-devel
rundeps    :
    - devel:
        - haskell-digest-devel
        - haskell-old-time-devel
        - haskell-zlib-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
