name       : haskell-zip-archive
version    : 0.3.2.4
release    : 2
source     :
    - https://hackage.haskell.org/package/zip-archive-0.3.2.4/zip-archive-0.3.2.4.tar.gz : 20612ed34d8d14deef120440c75f951a5c92c9f39f0de1b82ebac6d5923b3785
license    : BSD-3-Clause
component  : programming.haskell
summary    : The zip-archive library provides functions for creating, modifying, and extracting files from zip archives.
description: |
    The zip-archive library provides functions for creating, modifying, and extracting files from zip archives.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-digest
    - haskell-mtl
    - haskell-old-time
    - haskell-text
    - haskell-zlib
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
