name       : haskell-zip-archive
version    : 0.3.0.5
release    : 1
source     :
    - http://hackage.haskell.org/package/zip-archive-0.3.0.5/zip-archive-0.3.0.5.tar.gz : dc83366e44d735df4088eb174c02c35a522e6228c04fecc35fe9493299fc97c7
license    : BSD-3-Clause
component  : programming.haskell
summary    : The zip-archive library provides functions for creating, modifying, and extracting files from zip archives.
description: |
    The zip-archive library provides functions for creating, modifying, and extracting files from zip archives.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-digest
    - haskell-old-time
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register